# --- Automatycznie wygenerowany plik SonarQube ---
    sonar.projectKey=Project
    sonar.projectName=Project
    sonar.sources=repo
    sonar.sourceEncoding=UTF-8
    sonar.host.url=http://sonarqube:9000
    sonar.login=squ_d477d744c781c7e4cd7ca38cc176257976e52da4
    sonar.python.version=3

    # Wykluczenia z analizy
    sonar.exclusions=**/*.csv,**/venv/**,**/*.json,**/*.xml,**/*.yml,**/*.yaml,**/*.png,**/*.jpg,**/*.md,**/*.ico
    